config/routes.rb
Rails.application.routes.draw do
  root to: "gift#index"

  # get 'index/:id/edit', to: 'gift#edit'
  resources :gifts, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < Airrecord::Table
  self.base_key = "appsnmy0OMuSEkwJS"
  self.table_name = "Weddings C&J"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gift_controller.rb
Airrecord.api_key = ENV["AIRTABLE_API_KEY"]

class GiftController < ApplicationController
  def index
    @gifts = Gift.all(sort: { "id" => "asc"})
  end

  def show
    @gift = Gift.find(params[:id])
  end

  # def edit
  #   @gift = Gift.find(params[:id])
  # end
end

  private

  def gift_params
    params.require(:gift).permit(
      :gift,
      :name,
      :initialPrice,
      :remainingPrice
    )
  end

app/controllers/pages_controller.rb
# require './app/services/airtable_api_handler.rb'


class PagesController < ApplicationController
  def home
    # @result = AirtableApiHandler.get_all_rows

#     # @final = @result.map do |e| {
#     #   e
#     # }
#     # return @final

#     # raise
#     # return @result["fields"]
#     # remaining_price = [:id, :remainingPrice]
#     # @result.map do |r|
#       # r.select { |k,_| remaining_price.include? k }
#     # end
#     # return remaining_price

#     # @initial_price = @result[0]
#     # @remaining_price = @result[0]
#     # @gift_name = @result["fields"]["gift"]
  end

#   def show
#     # @result
#     # => "asc"
#   end

#   def addValue
#     # @value.update
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gift_helper.rb
module GiftHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gift/index.html.erb
<!-- <div class="container-header"> -->
  <div class="background-img">
    <div class="container-title">
      <h1>Liste de Mariage</h1>
      <h2>Cindy&ensp;& Jérémie</h2>
      <h3>J - <div id="days"></div><div id="end"></div></h3>
    </div>
  </div>
<!-- </div> -->
<div id="section2">
  <img src="assets/hero-banner.png" alt="Mariage Hero Banner">
    <div class="container-core">
      <p>La tradition des mariages invite à partager une liste de mariage.
      Depuis 10 ans que nous sommes ensemble, nous avons su nous équiper de sorte à créer notre petit cocon.
      Cependant nos choix de vie ont fait que nous avons peu voyagé en amoureux.
      A ce titre nous souhaitons effectuer notre voyage de noces en Martinique.</p>
      <img src="assets/diamant-martinique.jpg" alt="Rocher du Diamant Martinique">
      <p>Ainsi nous réalisons cette liste de mariage autour de cet évènement que nous planifions en février 2022.
      </br></br>
      A travers ce site internet vous allez pouvoir contribuer à notre voyage de noces en vous positionnant sur différents cadeaux.
      Vous pouvez soit vous engager sur un montant en vue de le mettre dans l’urne
      (espèce, chèque, mais ne mettez pas un bras car l’urne est trop petite),
      soit en effectuant directement le paiement en ligne via votre compte paypal.</p>
      <img src="assets/arrow.png" alt="Arrow separation">
      <p>Si vous avez gagné au loto, à un jeu à gratter, ou que vous venez d’avoir une augmentation,
      vous pouvez vous positionner sur l’intégralité d’un cadeau (faites vous plaisir, nous sommes preneurs).
      </br></br>
      Vous pouvez également vous positionner sur une partie d’un ou de plusieurs cadeaux.
      Une fois validé, le montant restant apparaitra pour les autres personnes se connectant.
      </br></br>
      Enfin une dernière possibilité est la participation libre. Vous verrez c’est tout en bas.
      Cette participation correspond à une cagnotte qui pourra compléter des cadeaux qui n’ont pas atteint le montant à 100%,
      ou bien nous permettre de faire d’autres activités une fois en Martinique.
      </br></br>
      Pour vous encourager à nous faire plaisir, voici notre but :</p>
      <div class="container-square">
        <img src="assets/plongee-tortue.jpg" alt="Plongée tortue Martinique">
        <img src="assets/restaurant.jpg" alt="Restaurant Martinique">
        <img src="assets/rocher-diamant.jpg" alt="Rocher du Diamant Martinique">
        <img src="assets/salines.jpg" alt="Plage les Salines Martinique">
      </div>
      <p>Sélectionnez la ou les lignes auxquels vous souhaitez participer :</p>
      <img src="assets/alliances.png" alt="Alliances C&J">
    </div>
  </div>
</div>
<div id="section3">

  <ul id="table" class="container-grid">
    <div class="items" style="background-color: white;">
      <div class="header-grid-1"></div>
      <div class="header-grid-2">
        Montant <strong>Initial</strong>
      </div>
      <div class="header-grid-3">
        Montant <strong>Restant</strong>
      </div>
      <div class="header-grid-4">
        Votre <strong>Participation</strong>
      </div> <!-- Table's Head -->
    </div>

    <% @gifts.each_with_index do |gift, index| %>
      <% if !gift.fields.empty? %>
      <%#= render 'shared/modal', id: gift.fields["id"] %>

        <!-- MODAL -->
        <div id="myModal" class="modal">
          <div class="modal-content">
            <span class="close">&times;</span>

            <!-- FORM -->
            <%= gift.fields["gift"] %>
            <%#= render 'shared/form' %>
            <%= simple_form_for "" do |f| %>
              <%= gift.fields["id"] %>
              <%= f.input :montant, as: :integer %>
              <%#= f.input :value, as: :integer %>
              <%= f.button :submit, value: "Participer" %>
            <% end %>
            <!-- END FORM -->

            <input type="number" min="0" max="#{gift.fields['remainingPrice']}" id="content_number_form">
            <button id="validate_form">Click</button>
          </div>
        </div>
        <!-- END MODAL-->

          <div href="" class="myBtn" id="link">
            <!-- lignes impaires -->
            <% if index.odd? %>
              <div class="items bck-pink">
                <li style="padding-left: 20px;"><%= gift["gift"] %></li>
                <li><%= gift.fields["initialPrice"] %>€</li>
                <li><%= gift.fields["remainingPrice"] %>€</li>
                <li class="value_submited">-</li>
              </div>
            <% else %>
              <!-- lignes paires -->
              <div class="items bck-green">
                <li style="padding-left: 20px;"><%= gift["gift"] %></li>
                <li><%= gift.fields["initialPrice"] %>€</li>
                <li><%= gift.fields["remainingPrice"] %>€</li>
                <li>-<%= @valueSubmited %></li>
              </div>
            <% end %>
          </div>
        <%# end %>
      <% end %>
    <% end %>

  </ul>
</div>

<footer>
  <p>Réalisation unique pour la célébration de Cindy & Jérémie // Jonathan V. // 2021</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariageCJ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Pacifico&family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">    <link href="//db.onlinewebfonts.com/c/39fc8df1369bc314ee2ba31126b8fee7?family=Stringfellows" rel="stylesheet" type="text/css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
      const myBtns = document.querySelectorAll(".myBtn");
      const modal = document.getElementById("myModal");
      const span = document.getElementsByClassName("close")[0];

      myBtns.forEach((myBtn) => {
        myBtn.onclick = function() {
        modal.style.display = "block";
        }
      })
      span.onclick = function() {
        modal.style.display = "none";
      }
      window.onclick = function(event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      }

      const valueSubmit = document.querySelector('value_submited');

      valueSubmit.innerHTML.replace('-', '20');

      // const popModal = (e) => {
      //   e.preventDefault();
      //   modal.style.display = "block";
      // }

      // const outModal = (e) => {
      //   e.preventDefault();
      //   modal.style.display = "none";
      //   if (event.target == modal) {
      //     modal.style.display = "none";
      //   }
      // }

      // const initModal = () => {
      //   if (link) {
      //     link.addEventListener('click', popModal);
      //   }
      //   if (span) {
      //     modal.addEventListener('click', outModal);
      //   }
      // }
      // $('#prevent-reloading').submit(function (e) {
      //   e.preventDefault();
      // });
      // $('#prevent-reloading').click(function (e) {
      //   e.preventDefault();
      // });

    </script>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <div class="container-header"> -->
  <div class="background-img">
    <div class="container-title">
      <h1>Liste de Mariage</h1>
      <h2>Cindy&ensp;& Jérémie</h2>
      <h3>J - <div id="days"></div><div id="end"></div></h3>
    </div>
  </div>
<!-- </div> -->
<div id="section2">
  <img src="assets/hero-banner.png" alt="Mariage Hero Banner">
    <div class="container-core">
      <p>La tradition des mariages invite à partager une liste de mariage.
      Depuis 10 ans que nous sommes ensemble, nous avons su nous équiper de sorte à créer notre petit cocon.
      Cependant nos choix de vie ont fait que nous avons peu voyagé en amoureux.
      A ce titre nous souhaitons effectuer notre voyage de noces en Martinique.</p>
      <img src="assets/diamant-martinique.jpg" alt="Rocher du Diamant Martinique">
      <p>Ainsi nous réalisons cette liste de mariage autour de cet évènement que nous planifions en février 2022.
      </br></br>
      A travers ce site internet vous allez pouvoir contribuer à notre voyage de noces en vous positionnant sur différents cadeaux.
      Vous pouvez soit vous engager sur un montant en vue de le mettre dans l’urne
      (espèce, chèque, mais ne mettez pas un bras car l’urne est trop petite),
      soit en effectuant directement le paiement en ligne via votre compte paypal.</p>
      <img src="assets/arrow.png" alt="Arrow separation">
      <p>Si vous avez gagné au loto, à un jeu à gratter, ou que vous venez d’avoir une augmentation,
      vous pouvez vous positionner sur l’intégralité d’un cadeau (faites vous plaisir, nous sommes preneurs).
      </br></br>
      Vous pouvez également vous positionner sur une partie d’un ou de plusieurs cadeaux.
      Une fois validé, le montant restant apparaitra pour les autres personnes se connectant.
      </br></br>
      Enfin une dernière possibilité est la participation libre. Vous verrez c’est tout en bas.
      Cette participation correspond à une cagnotte qui pourra compléter des cadeaux qui n’ont pas atteint le montant à 100%,
      ou bien nous permettre de faire d’autres activités une fois en Martinique.
      </br></br>
      Pour vous encourager à nous faire plaisir, voici notre but :</p>
      <div class="container-square">
        <img src="assets/plongee-tortue.jpg" alt="Plongée tortue Martinique">
        <img src="assets/restaurant.jpg" alt="Restaurant Martinique">
        <img src="assets/rocher-diamant.jpg" alt="Rocher du Diamant Martinique">
        <img src="assets/salines.jpg" alt="Plage les Salines Martinique">
      </div>
      <p>Sélectionnez la ou les lignes auxquels vous souhaitez participer :</p>
      <img src="assets/alliances.png" alt="Alliances C&J">
    </div>
  </div>
</div>
<div id="section3">


  <ul id="table" class="container-grid">
    <div class="items" style="background-color: white;">
      <div class="header-grid-1"></div>
      <div class="header-grid-2">
        Montant <strong>Initial</strong>
      </div>
      <div class="header-grid-3">
        Montant <strong>Restant</strong>
      </div>
      <div class="header-grid-4">
        Votre <strong>Participation</strong>
      </div>
    </div>

    <% @result.each_with_index do |line, index| %>
      <%= render 'shared/modal' %>
      <div href="" class="myBtn" id="link">
        <% if index.odd? %>
          <div class="items bck-pink">
            <li style="padding-left: 20px;"><%= "#{line["fields"]["gift"]}" %></li>
            <li><%= "#{line["fields"]["initialPrice"]}€" %></li>
            <li><%= "#{line["fields"]["remainingPrice"]}€" %></li>
            <li><%= @valueSubmited %></li>
          </div>
        <% else %>
          <div class="items bck-green">
            <li style="padding-left: 20px;"><%= "#{line["fields"]["gift"]}" %></li>
            <li><%= "#{line["fields"]["initialPrice"]}€" %></li>
            <li><%= "#{line["fields"]["remainingPrice"] #- @valueSubmited
                } €" %></li>
            <li><%= @valueSubmited %></li>
          </div>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

<footer>
  <p>Réalisation unique pour la célébration de Cindy & Jérémie // Jonathan V. // 2021</p>
</footer>

app/views/shared/_form.html.erb
<%#= form_with gift_path method: :post do |value_form| %>
  <%#= value_form.label :remainingPrice, "Montant" %>
  <%#= value_form.number_field :remainingPrice %>
  <%#= value_form.submit "Ajouter"%>
<%# end %>


<!-- Gift.find(id) -->
<!-- <input type="" name=""> //JS = récupérer -->
<!-- gift["remainingprice"] -= input -->
<!-- gift.save -->
<!-- redirect_to -->

<%= gift.fields["id"] %>
<input type="" name=""> //JS = récupérer
gift["remainingprice"] -= input
gift.save
redirect_to


<%#= simple_form_for(gift_path), remote: true do |value_form| %>
  <%#= value_form.input :remainingPrice %>
  <%#= value_form.button value: "Ajouter" %>
<%# end %>

app/views/shared/_modal.html.erb
<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <%= gift.fields["id"] %>
    <%#= render 'shared/form' %>
  </div>
</div>